---
title: "Ejercitario 1"
subtitle: "Diferentes formas de medir el PIB"
format:
  revealjs: 
    slide-number: true
    scrollable: true
    chalkboard: 
      buttons: true
    preview-links: true
    theme: default
  pdf:
    toc: false
    toc-depth: 3
    number-sections: false
    colorlinks: true
---

## Sachs, Jeffrey y Larraín, Felipe. (1994).

Macroeconomía en la Economía Global. `Capítulo 2`, Los conceptos básicos en la macroeconomía.

-   Distintas `medidas del ingreso` y del `producto` agregados, así como sus relaciones.

-   La función de los precios y los índices de precios.

-   ...

## Producto Interno Bruto (PIB)

Es el valor total de la **producción corriente** de **bienes y servicios finales** dentro del territorio nacional durante un período de tiempo, expresado en una **unidad de medida común**, generalamente en una unidad monetaria.

-   *"`producción corriente`"* no se cuenta la reventa de artículos producidos en un período anterior.

-   *"`bienes finales`"* no se cuenta el valor de las materias primas y los bienes intermedios (semi-terminados) que se utilizan como insumos para la producción de otros bienes.

## Diferentes formas de medir el PIB

-   El PIB es la suma de todas las **compras finales** o demandas finales de productos en la economía.

-   Es la suma del **valor agregado** por todas las empresas de la economía.

-   Es la suma de todos los **ingresos de los factores** de producción (trabajo y capital) en la economía.

## Diferentes formas de medir el PIB

-   Método del [Gasto]{.underline} (compras finales).

-   Método del [Producto]{.underline} (valor agregado).

-   Método del [Ingreso]{.underline} (ingreso de los factores).

Todos dan el mismo resultado[^1]

[^1]: Se pueden presentar pequeñas diferencias entre las tres medidas debido a errores en los datos.

## Método del Gasto {.center}

$$
PIB=C+I+G+NX
$$

$C$ : es el consumo familiar

$I$ : inversión en capital nuevo para la economía

$G$ : consumo del gobierno

$NX$ : ventas netas al extranjero

## Método del Producto

$$
PIB = \sum_{j:1}^{n}{VAB_j}
$$

$$
VAB_j = VBP_j - CI_j
$$

$$
PIB = VAB + Ti - S
$$

Considerando impuestos indirectos y subvenciones

## Método del Ingreso

-   Suma los ingresos de todos los factores (trabajo y capital) que contribuyen al proceso productivo.

-   El **Ingreso Doméstico (ID)**, estrechamente [relacionado]{.underline} con el PIB, es la suma del ingreso del **trabajo** **(W)** y el ingreso del **capital (R)**. $ID = W + R$

-   Ingreso Laboral: compensación de los empleados asalariados.

-   Ingreso del Capital: abarcan el ingreso de los trabajadores independientes, ingreso por intereses, por arrendamiento y las utilidades empresariales.

## Método del Ingreso

-   Hay dos factores que hacen que el ingreso doméstico [no sea exactamente igual]{.underline} al PIB: la **depreciación** del stock de capital **(DN)** y los **impuestos** **indirectos (Ti)**.

-   Cuando al PIB se le resta la depreciación se obtiene el Producto Interno Neto (PIN). $PIN = PIB - DN$

-   PIB, a precios de mercado; PIN, a precios después de impuestos. La [diferencia]{.underline} son los Ti. $PIB = PIN - Ti$

$$ ID = PIN - Ti = (PIB - DN) - Ti $$

## Método del Ingreso

$$ ID = PIN - Ti = (PIB - DN) - Ti $$

$$ PIB = ID + DN + Ti $$

$$ PIB = (W + R) + DN + Ti $$

## Considerando el mercado abierto al resto del mundo

$$
PNB = PIB + PNF
$$

$$
PIB = W + R + DN + Ti - PNF
$$

$$
PIB = ID + DN + Ti - PNF
$$

**Pago Neto a Factores (PNF):** ingreso neto recibido por factores de producción nacionales desde el exterior.

**PNB:** Producto Nacional Bruto.

## PIB Nominal y PIB Real {.center}

$$
PIB_{Nominal} = \sum_{i = 0}^{n}{P_{i,t}*Q_{i,t}}
$$

$$
PIB_{Real} = \sum_{i = 0}^{n}{P_{i,0}*Q_{i,t}}
$$

$P_0$ considera precio [constante]{.underline} de un **año base**.

## PIB Nominal y PIB Real

-   $P_{i, t}$: precio de un bien o [servicio específico]{.underline} $i$ en un [momento]{.underline} $t$. Por ejemplo, el precio de una tonelada de trigo en el año $t$.

-   $Q_{i, t}$: cantidad producida del bien o servicio específico $i$ en el momento $t$.

-   $\sum_{i = 0}^{n}$: suma de todos los bienes y servicios producidos en la economía, desde el primero ($i = 0$) hasta el último ($i = n$). El símbolo $i$ representa cada uno de estos bienes y servicios, y $n$ es el número total de bienes y servicios.

## Cálculo de índices

[Deflactor implícito del PIB (]{.underline}$DI$)

$$
DI = \frac{PIB_{Nominal}}{PIB_{Real}}
$$

[Índice de Precios al Consumidor (]{.underline}$IPC$)

$$
IPC_t = \sum_{i = 0}^{n}{ w_{i, 0} * \frac{P_{i, t}}{P_{i, 0}}}
$$

$w_0$ : ponderador fijo en año base.

$DI$: Todos los productos $IPC$: Canasta representativa

## Para muchos productos en un periodo

Con ponderadores fijos

$$
IPC_t = w_{1, 0} *( \frac{P_{1, t}}{P_{1, 0}}) + w_{2, 0} *( \frac{P_{2, t}}{P_{2, 0}}) + ... + w_{n, 0} *( \frac{P_{n, t}}{P_{n, 0}})
$$

Cálculo de los ponderadores

$$
w_0 = P_0 * \frac{Q_0}{PIB_{Nominal, 0}}
$$

## Para muchos productos en un periodo

Mediante índice [Laspeyres]{.underline}

$$ IP_{L} = \frac{\sum{P_t * Q_0}}{\sum{P_{0} * Q_0}} * 100 $$

Mediante índice [Paasche]{.underline}

$$
IP_{P} = DI = \frac{\sum{P_t * Q_t}}{\sum{P_{0} * Q_t}} * 100
$$

El **IPC** es un índice Laspeyres

El **DI** es un índice Paasche

## Para toda la economía en varios periodos

sdsd

## Ejercicio 1

**La macroeconomía es una rama de la ciencia económica cuya aplicación a la vida diaria es casi inmediata ¿Cuál es la situación macroeconómica del Paraguay actualmente?**

Visite las páginas web del [**BCP**](https://www.bcp.gov.py/)**, [Hacienda](https://www.mef.gov.py/web-hacienda/index.php), [INE](https://www.ine.gov.py/)** **u otras** como [Banco Mundial](https://www.bancomundial.org/es/home), [FMI](https://www.imf.org/en/Data), [CEPAL](https://statistics.cepal.org/portal/cepalstat/index.html?lang=es), [OCDE](https://data.oecd.org/) y busque los indicadores macroeconómicos más importantes y **confeccione un cuadro comparativo** con un país europeo, un país asiático y un país latinoamericano.

## Ejercicio 1

**Indicadores macroeconómicos:** PIB, inflación, desempleo, tipos de interés, productividad.

-   PIB = tasa de crecimiento, tendencia, pronóstico.

-   IPC = inflación, comportamiento, fluctuación.

-   Moneda = fortaleza, estabilidad, tipos de interés.

-   Mercado laboral = empleo, comportamiento.

## Ejercicio 2

El valor de las transacciones siguientes ¿Debe incluirse o no como parte del PIB? ¿Por qué no?

a.  Un turista paga una **comida** en un restaurante.

b.  Una compañía compra un **edificio** **antiguo**.

c.  Un proveedor vende chips de computadora a una **empresa que fabrica** computadoras.

d.  Un consumidor compra un automóvil a un **distribuidor**.

## Ejercicio 2

a\) Un turista paga una **comida** en un restaurante.

-   `Sí` porque incluye **bienes y servicios finales** dentro del territorio nacional.

b\) Una compañía compra un **edificio** **antiguo**.

-   `No` contribuye al PIB porque es una transferencia de un activo ya existente. En el momento de su construcción ya fue contabilizado.

c\) Un **proveedor** vende chips de computadora a una **empresa que fabrica** computadoras.

-   `No` porque se contabilizan solo los bienes finales y no se consideran las materias primas.

d\) Un consumidor compra un automóvil a un **distribuidor**.

-   `Sí`, pero solo cuando es de **producción nacional** y la distribuidora se lo compra al fabricante.

-   En caso de que sea una **importación** por parte de la distribuidora será esta la transacción a ser contabilizada.

::: footer
2.  ¿Debe incluirse o no como parte del PIB? ¿Por qué no?
:::

## Ejercicio 3

Considere una economía simple con sólo 3 artículos. El precio de mercado de cada artículo es: $P_1= 5$, $P_2=10$ y $P_3=15$.

La producción (y el consumo) de cada artículo durante $1990$ fue: $Q_1 = 20$; $Q_2 = 25$ y $Q_3 = 10$.

Suponga que en $1991$ los precios suben a: $P_1= 6$, $P_2=12$ y $P_3= 17$ y las cantidades producidas (y consumidas) pasan a: $Q_1 = 21$; $Q_2= 27$ y $Q_3 = 11$.

## Ejercicio 3

[Determine]{.underline}:

a.  El valor del `PIB nominal` de cada año.
b.  `Índice de precios al consumidor` usando como ponderadores la participación de cada artículo en el consumo total.
c.  Índice de precios considerando las fórmulas de `Laspeyres` y `Paasche`.
d.  El valor del `PIB real` del año 1991, usando 1990 como año base.
e.  La `inflación` y la `tasa de crecimiento real` de la economía.
f.  Que dice su respuesta respecto a la `importancia` de usar índices o deflactores de precios.

## 3.a. El valor del PIB Nominal

|          |       | $1990$  |          |     |       | $1991$  |          |
|:--------:|:-----:|:-------:|:--------:|-----|:-----:|:-------:|:--------:|
| Artículo | $P_1$ |  $Q_1$  | $P_1Q_1$ |     | $P_2$ |  $Q_2$  | $P_2Q_2$ |
|    1     |  $5$  |  $20$   |  $100$   |     |  $6$  |  $21$   |  $126$   |
|    2     | $10$  |  $25$   |  $250$   |     | $12$  |  $27$   |  $324$   |
|    3     | $15$  |  $10$   |  $150$   |     | $17$  |  $11$   |  $187$   |
|          |       |         |          |     |       |         |          |
|          |       | $PIB_1$ |  $500$   |     |       | $PIB_2$ |  $637$   |

$$a.1) PIB_1 = \sum_{i=0}^{n}{P_1 * Q_1} = 500$$

$$a.2) PIB_2 = \sum_{i=0}^{n}{P_2 * Q_2} = 637$$

::: footer
2.El valor del `PIB nominal` de cada año.
:::

## 3.b. `IPC` usando ponderadores

| Artículo |  Participación   |
|:--------:|:----------------:|
|    1     | $100/500 = 0,2$  |
|    2     | $250/500 = 0,5$  |
|    3     | $150/500 = 0,3$  |
|          |                  |
|          | $\sum{Part} = 1$ |

$$
IPC_t = w_{1, 0} *( \frac{P_{1, t}}{P_{1, 0}}) + w_{2, 0} *( \frac{P_{2, t}}{P_{2, 0}}) + w_{3, 0} *( \frac{P_{3, t}}{P_{3, 0}})
$$

$$
IPC_2 = w_{1, 1} ( \frac{P_{1, 2}}{P_{1, 1}}) + w_{2, 1} ( \frac{P_{2, 2}}{P_{2, 1}}) + w_{3, 1} ( \frac{P_{3, 2}}{P_{3, 1}})
$$

$$
IPC_2 = 0,2 ( \frac{6}{5}) + 0,5 ( \frac{12}{10}) + 0,3 ( \frac{17}{15}) = 1,18
$$

$$IPC_2 = 1,18 * 100 = 118$$

$$inflación = \pi = var \% IPC = \frac{(IPC_t - IPC_{t-1})}{IPC_{t-1}}$$

$$
\pi = \frac{(118-100)}{100} = 0,18 = 18\%
$$

::: footer
3.b. `Índice de precios al consumidor` usando ponderadores.
:::

## 3.c. IPC `Laspeyres` y `Paasche`

$$ IP_{L} = \frac{\sum{P_t * Q_0}}{\sum{P_{0} * Q_0}} * 100 $$

$$ IP_{L} = \frac{\sum{P_t * Q_0}}{\sum{P_{0} * Q_0}} * 100 $$

Mediante índice [Paasche]{.underline}

$$ IP_{P} = DI = \frac{\sum{P_t * Q_t}}{\sum{P_{0} * Q_t}} * 100 $$

El **IPC** es un índice Laspeyres

El **DI** es un índice Paasche

## Ejercicio 4

Usted conoce la siguiente información sobre la economía de Macrolandia, donde la producción se agrupa en tres sectores productivos (agrícola, industrial y servicios):

|                      |       |                      |     |
|----------------------|-------|----------------------|-----|
| Consumo              | 3.400 | PIB sector agrícola  | 940 |
| Ingreso doméstico    | 3.550 | Remuneración capital | 860 |
| PNB                  | 4.050 | Gastos públicos      | 500 |
| PIB industrial       | 1.450 | Exportaciones        | 600 |
| Impuestos indirectos | 50    |                      |     |

## Ejercicio 4

También se sabe que:

-   El `stock de capital` es dos veces el `PIB` y que la depreciación corresponde al 5% del stock de capital actual.

-   Las importaciones tienen como único destino el consumo, del cual representan el 40%.

-   No existen impuestos directos.

Con dicha información calcule: a) el **PIB** del sector servicios b) el **PIB** del total c) el **pago** **neto** **a** **factores** d) las remuneraciones a los **trabajadores** y; e) la **inversión** **bruta** y **neta**.

## Ejercicio 5

Supongamos una economía donde el `consumo agregado` es igual a **100**, la `inversión` igual a **80**, se pagan `impuestos` por un total de **10**, las `exportaciones` ascienden a **15** y las `importaciones` a **5**.

Además, el `gobierno` no posee deudas y gasta el total de sus ingresos.

a.  Calcular el `PIB.`
b.  Calcular el `ahorro privado`, el ahorro `público` y el ahorro `externo`.
c.  Muestre la `igualdad ahorro-inversión`.

## Ejercicio 6

Un `PIB per cápita más` alto ¿Implica necesariamente mayor `bienestar`?

## Ejercicio 7

Señale el tipo de sesgo que existe en la medición del `índice de precios al consumidor` frente a los siguientes hechos:

a.  La aparición de múltiples plataformas de streaming.
b.  El lanzamiento anual de novedosos y cada vez más potentes smartphones
c.  La aparición de grandes establecimientos comerciales con ofertas muy interesantes para los consumidores.
d.  El incremento del precio de la mantequilla frente a la margarina.
